[package]
name = "hera"
version = "0.1.0"
authors = ["Tejas Agarwal <tejasagarwalbly@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
